# Generated by Django 3.1 on 2022-12-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Annoying Blog!', max_length=255),
        ),
    ]
