# Generated by Django 4.1.4 on 2022-12-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='ahahahaha', max_length=255),
        ),
    ]
