# Generated by Django 4.1.4 on 2022-12-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_profile_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
